# syncPolicy will allow you configure your default autosync configurations
# for instance, `syncPolicy.automated={}` demonstrated below
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
gitops:
  repoURL: git@github.com:krumIO/cloud-native-cicd-starter.git
  values: app-of-apps-values.yaml
spec:
  applications:
    - name: umbrella
      path: helm/example-umbrella
      repoURL: git@github.com:krumIO/cloud-native-workshop-charts.git
      targetRevision: HEAD
    # - name: baseline-react
    #   path: helm/baseline-react-app
    #   repoURL: git@github.com:krumIO/cloud-native-workshop-charts.git
    #   targetRevision: HEAD
    # - name: baseline-vue
    #   path: helm/baseline-vue-app
    #   repoURL: git@github.com:krumIO/cloud-native-workshop-charts.git
    #   targetRevision: HEAD
    # - name: baseline-laravel
    #   path: helm/baseline-laravel-app
    #   repoURL: git@github.com:krumIO/cloud-native-workshop-charts.git
    #   targetRevision: HEAD
    # - name: python-hello-world
    #   path: helm/python-docs-hello-world
    #   repoURL: git@github.com:krumIO/cloud-native-workshop-charts.git
    #   targetRevision: HEAD
  environments:
    - name: development
      path: environments/development
      targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: development
    - name: staging
      path: environments/staging
      targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: staging
    - name: production
      path: environments/production
      targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: production
      # exempt production from automated syncs
      syncOverrides:
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
      # filter applications that make it to production
      applicationFilter:
        - umbrella

