# Default values for argo-workflows.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
docker:
  server: docker.io
  prefix: krumware/
  secretName: docker-push-user

github:
  # github repository owner
  owner: krumIO
  # the list of repositories to build on push events
  repositories:
    python-docs-hello-world:
      values: python-hello-world-values.yaml
      branches:
        master: "python-docs-hello-world"
    baseline-react-app:
      values: baseline-react-values.yaml
      branches:
        main: "baseline-react-app"
    baseline-vue-app:
      values: baseline-vue-values.yaml
      branches:
        main: "baseline-vue-app"
    example-laravel-app:
      values: baseline-laravel-values.yaml
      branches:
        main: "example-laravel-app"
    baseline-golang-app:
      values: baseline-golang-values.yaml
      branches:
        main: "baseline-golang-app"
  # configures where automated tagging commits are sent
  automateCommits: false
  deploymentRepository: cloud-native-cicd-starter
  deploymentFolderPath: environments/development

  # configures our expected inbound webhook route which Github will be 
  webhook:
    domain: rancher.131.153.227.137.sslip.io
    hostname: https://rancher.131.153.227.137.sslip.io
    port: 12000
    endpoint: /api/webhook

  # allows webhook creation & commit automation  
  machineUserToken:
    name: github-machine-user
    key: token

  # githubApp:
  #   privateKey:
  #     name: repo-secret-name
  #     key: githubAppPrivateKey
  #   appID: 123456
  #   installationID: 12345678